app = "tempowaiter-staging"
primary_region = "waw"

[build]

[env]
SPRING_DATASOURCE_PASSWORD = "compose-postgres"
SPRING_DATASOURCE_URL = "jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/staging"
SPRING_DATASOURCE_USERNAME = "postgres.ruexpbcygjdotksrkzbn"
swap_size_mb = "512"

[http_service]
internal_port = 8080
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
[concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 1000

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512