# fly.production.toml app configuration file generated for tempowaiter on 2023-11-09T21:43:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tempowaiter"
primary_region = "waw"

[build]

[env]
  SPRING_DATASOURCE_URL = "jdbc:postgresql://146.59.93.121:5432/tempowaiter?sslmode=disable"
  SPRING_DATASOURCE_USERNAME = "compose-postgres"
  SPRING_DATASOURCE_PASSWORD = "a-password"
  swap_size_mb = "512"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512